# Generated by Django 5.1.4 on 2025-11-09 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afiliado',
            name='lider',
        ),
        migrations.AddField(
            model_name='afiliado',
            name='es_lider_comunitario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='lider_vinculado',
            field=models.ForeignKey(blank=True, limit_choices_to={'es_lider_comunitario': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referidos', to='afiliados_app.afiliado'),
        ),
        migrations.DeleteModel(
            name='LiderComunitario',
        ),
    ]
