# Generated by Django 5.1.4 on 2026-09-23 17:39

import afiliados_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi', models.CharField(db_index=True, max_length=13, unique=True)),
                ('foto', models.ImageField(upload_to=afiliados_app.models.foto_persona_upload_to)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='afiliado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=afiliados_app.models.foto_persona_upload_to),
        ),
    ]
