# Generated by Django 5.1.4 on 2025-10-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados_app', '0002_insumosolicitud_delete_detallesolicitudcompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='insumos',
            field=models.ManyToManyField(blank=True, related_name='solicitudes', to='afiliados_app.insumo'),
        ),
    ]
