# Generated by Django 5.1.4 on 2025-11-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados_app', '0002_remove_afiliado_lider_afiliado_es_lider_comunitario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleccion2023',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.IntegerField(blank=True, null=True)),
                ('todos', models.IntegerField(blank=True, null=True)),
                ('cambio', models.IntegerField(blank=True, null=True)),
                ('morena', models.IntegerField(blank=True, null=True)),
                ('vamos', models.IntegerField(blank=True, null=True)),
                ('pin', models.IntegerField(blank=True, null=True)),
                ('renovador', models.IntegerField(blank=True, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('azul', models.IntegerField(blank=True, null=True)),
                ('une', models.IntegerField(blank=True, null=True)),
                ('fcn_nacion', models.IntegerField(blank=True, null=True)),
                ('podemos', models.IntegerField(blank=True, null=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('votos_blanco', models.IntegerField(blank=True, null=True)),
                ('votos_nulos', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('votos_invalidos', models.IntegerField(blank=True, null=True)),
                ('impugnaciones', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('centro_votacion', models.TextField(blank=True, null=True)),
                ('secnum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'elecciones_2023',
            },
        ),
    ]
