# Generated by Django 5.1.4 on 2025-10-16 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados_app', '0003_solicitudcompra_insumos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariodepartamento',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='departamento',
        ),
        migrations.DeleteModel(
            name='FechaInsumo',
        ),
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='insumos',
        ),
        migrations.RemoveField(
            model_name='insumosolicitud',
            name='insumo',
        ),
        migrations.AlterUniqueTogether(
            name='insumosolicitud',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='insumosolicitud',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='subproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='seccion',
        ),
        migrations.RemoveField(
            model_name='usuariodepartamento',
            name='seccion',
        ),
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='subproducto',
        ),
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='subproducto',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='usuariodepartamento',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usuariodepartamento',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Insumo',
        ),
        migrations.DeleteModel(
            name='InsumoSolicitud',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
        migrations.DeleteModel(
            name='Subproducto',
        ),
        migrations.DeleteModel(
            name='SolicitudCompra',
        ),
        migrations.DeleteModel(
            name='UsuarioDepartamento',
        ),
    ]
