# Generated by Django 5.1.4 on 2025-11-20 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados_app', '0004_sector_afiliado_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunidades', to='afiliados_app.sector'),
        ),
    ]
