# Generated by Django 5.1.4 on 2025-11-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados_app', '0005_comunidad_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='centros_votacion',
            field=models.ManyToManyField(blank=True, related_name='sectores', to='afiliados_app.centrovotacion'),
        ),
    ]
