# Generated by Django 5.1.4 on 2025-11-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados_app', '0006_sector_centros_votacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='centros_votacion',
        ),
        migrations.AddField(
            model_name='centrovotacion',
            name='sectores',
            field=models.ManyToManyField(blank=True, related_name='centros', to='afiliados_app.sector'),
        ),
    ]
