# Generated by Django 5.1.4 on 2025-12-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados_app', '0007_remove_sector_centros_votacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrepCentroResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRESIDENTE', 'Presidente y Vicepresidente'), ('DIPUTADOS', 'Diputados'), ('PARLACEN', 'Parlacen'), ('ALCALDE', 'Alcalde')], max_length=20)),
                ('departamento', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('centro_codigo', models.CharField(db_index=True, max_length=20)),
                ('centro_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('mesa', models.CharField(db_index=True, max_length=20)),
                ('acta_url', models.TextField(blank=True, null=True)),
                ('partidos', models.JSONField()),
                ('votos_blanco', models.IntegerField(default=0)),
                ('votos_nulos', models.IntegerField(default=0)),
                ('votos_total', models.IntegerField(default=0)),
                ('votos_invalidos', models.IntegerField(default=0)),
                ('impugnaciones', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resultado por Mesa',
                'verbose_name_plural': 'Resultados por Mesa',
                'unique_together': {('tipo', 'centro_codigo', 'mesa')},
            },
        ),
    ]
