# Generated by Django 5.1.4 on 2025-12-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados_app', '0008_trepcentroresultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadronElectoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('comunidad', models.CharField(blank=True, max_length=255, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
