# Generated by Django 5.1.4 on 2026-02-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afiliados_app", "0009_padronelectoral"),
    ]

    operations = [
        migrations.AddField(
            model_name="afiliado",
            name="cargo_en_comision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COORDINADOR", "Coordinador"),
                    ("SECRETARIO", "Secretario"),
                    ("INTEGRANTE", "Integrante"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
