# Generated by Django 5.1.4 on 2026-02-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("afiliados_app", "0010_afiliado_cargo_en_comision"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="institucion",
            options={
                "permissions": (
                    ("view_elecciones_2023", "Puede ver el módulo de Elecciones 2023"),
                    ("view_cargar_padron", "Puede ver y usar la carga de padrón"),
                    ("view_configuracion", "Puede ver configuración institucional"),
                    ("view_usuarios", "Puede gestionar usuarios"),
                    ("view_filtros", "Puede ver el módulo de filtros"),
                    ("view_dashboard", "Puede ver el dashboard principal"),
                )
            },
        ),
    ]
