# Generated by Django 5.1.4 on 2026-02-26 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afiliados_app", "0011_alter_institucion_options"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("url_name", models.CharField(max_length=120)),
                ("section", models.CharField(blank=True, max_length=120, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["section", "label"],
            },
        ),
        migrations.CreateModel(
            name="GroupMenuView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_views",
                        to="auth.group",
                    ),
                ),
                (
                    "view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_links",
                        to="afiliados_app.menuview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista habilitada por grupo",
                "verbose_name_plural": "Vistas habilitadas por grupo",
                "unique_together": {("group", "view")},
            },
        ),
    ]
