# Generated by Django 5.1.4 on 2026-04-21 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "afiliados_app",
            "0013_alter_institucion_options_organizacionintegrante_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacionintegrante",
            name="usuario_modificacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="integrantes_organizacion_modificados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
