# Generated by Django 5.1.4 on 2026-04-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados_app', '0015_alter_institucion_options_coordinadororganizacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institucion',
            options={},
        ),
        migrations.DeleteModel(
            name='GroupMenuView',
        ),
        migrations.DeleteModel(
            name='MenuView',
        ),
    ]
