# Generated by Django 5.1.4 on 2026-04-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "afiliados_app",
            "0015_alter_institucion_options_coordinadororganizacion_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lidercomunitarioorganizacion",
            name="dpi",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
