# Generated by Django 5.1.4 on 2026-04-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados_app', '0016_alter_institucion_options_and_more'),
        ('afiliados_app', '0016_alter_institucion_options_delete_groupmenuview_and_more'),
    ]

    operations = [
    ]
