# Generated by Django 5.1.4 on 2026-04-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados_app', '0017_alter_institucion_options_responsableterritorial_dpi_and_more'),
        ('afiliados_app', '0017_merge_20260421_1221'),
    ]

    operations = [
    ]
