# Generated by Django 5.1.4 on 2026-04-22 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afiliados_app", "0018_merge_20260421_1242"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoordinadorJuventud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=160)),
                ("dpi", models.CharField(blank=True, max_length=20, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "tipo_coordinacion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=15,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "centro_votacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinadores_juventud",
                        to="afiliados_app.centrovotacion",
                    ),
                ),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinadores_juventud",
                        to="afiliados_app.comunidad",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinadores_juventud",
                        to="afiliados_app.sector",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coordinadores_juv_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coordinadores_juv_modificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="EstructuraJuventud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_estructura", models.CharField(max_length=80)),
                ("nombre", models.CharField(max_length=160)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=15,
                    ),
                ),
                ("cantidad_integrantes", models.PositiveIntegerField(default=0)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "centro_votacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estructuras_juventud",
                        to="afiliados_app.centrovotacion",
                    ),
                ),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estructuras_juventud",
                        to="afiliados_app.comunidad",
                    ),
                ),
                (
                    "coordinador_responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estructuras_responsables",
                        to="afiliados_app.coordinadorjuventud",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estructuras_juventud",
                        to="afiliados_app.sector",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estructuras_juv_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estructuras_juv_modificadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="LiderJuvenil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=160)),
                ("dpi", models.CharField(blank=True, max_length=20, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=15,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "centro_votacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lideres_juventud",
                        to="afiliados_app.centrovotacion",
                    ),
                ),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lideres_juventud",
                        to="afiliados_app.comunidad",
                    ),
                ),
                (
                    "coordinador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lideres",
                        to="afiliados_app.coordinadorjuventud",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lideres_juventud",
                        to="afiliados_app.sector",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lideres_juv_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lideres_juv_modificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="ResponsableJuventud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=160)),
                ("dpi", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=15,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "centro_votacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsables_juventud",
                        to="afiliados_app.centrovotacion",
                    ),
                ),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsables_juventud",
                        to="afiliados_app.comunidad",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsables_juventud",
                        to="afiliados_app.sector",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsables_juv_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsables_juv_modificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="IncidenciaJuventud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_incidencia", models.CharField(max_length=120)),
                ("descripcion", models.TextField()),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                        ],
                        default="MEDIA",
                        max_length=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=15,
                    ),
                ),
                ("seguimiento", models.TextField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "centro_votacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidencias_juventud",
                        to="afiliados_app.centrovotacion",
                    ),
                ),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidencias_juventud",
                        to="afiliados_app.comunidad",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidencias_juventud",
                        to="afiliados_app.sector",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidencias_juv_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidencias_juv_modificadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsable_asignado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidencias_asignadas",
                        to="afiliados_app.responsablejuventud",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="ReunionJuventud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo_reunion",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("titulo", models.CharField(max_length=180)),
                ("responsables", models.TextField(blank=True, null=True)),
                (
                    "responsable_tipo",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "responsable_referencia_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("asistentes", models.PositiveIntegerField(default=0)),
                ("acuerdos", models.TextField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "estado_seguimiento",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En proceso"),
                            ("CUMPLIDO", "Cumplido"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "centro_votacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reuniones_juventud",
                        to="afiliados_app.centrovotacion",
                    ),
                ),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reuniones_juventud",
                        to="afiliados_app.comunidad",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reuniones_juventud",
                        to="afiliados_app.sector",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reuniones_juv_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reuniones_juv_modificadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EstructuraIntegranteJuventud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dpi", models.CharField(max_length=20)),
                ("nombre_completo", models.CharField(max_length=180)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=15,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integrantes_estructura_juventud",
                        to="afiliados_app.comunidad",
                    ),
                ),
                (
                    "usuario_registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integrantes_estructura_juventud_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estructura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrantes",
                        to="afiliados_app.estructurajuventud",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_registro"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("estructura", "dpi"),
                        name="uniq_estructura_juventud_integrante_dpi",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JuventudIntegrante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("REVISADO", "Revisado"),
                            ("APROBADO", "Aprobado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "afiliado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_juventud",
                        to="afiliados_app.afiliado",
                    ),
                ),
                (
                    "usuario_modificacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integrantes_juventud_modificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integrantes_juventud_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Integrante de Juventud",
                "verbose_name_plural": "Integrantes de Juventud",
                "ordering": ["-fecha_creacion"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("afiliado",), name="uniq_juventud_afiliado"
                    )
                ],
            },
        ),
    ]
