# Generated by Django 5.1.4 on 2026-04-23 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afiliados_app", "0021_bancomedios_coordinadorcomunicacion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoberturaVisitaPlanHormiga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comunidades_atendidas", models.PositiveIntegerField(default=0)),
                ("comunidades_pendientes", models.PositiveIntegerField(default=0)),
                ("sectores_visitados", models.PositiveIntegerField(default=0)),
                ("sectores_pendientes", models.PositiveIntegerField(default=0)),
                ("fecha_corte", models.DateField()),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coberturas_plan_hormiga_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coberturas_plan_hormiga_modificadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_corte", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CoordinadorPlanHormiga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=160)),
                ("dpi", models.CharField(blank=True, max_length=20, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "tipo_coordinacion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=15,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "centro_votacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinadores_plan_hormiga",
                        to="afiliados_app.centrovotacion",
                    ),
                ),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinadores_plan_hormiga",
                        to="afiliados_app.comunidad",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinadores_plan_hormiga",
                        to="afiliados_app.sector",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coordinadores_plan_hormiga_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coordinadores_plan_hormiga_modificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="EnlaceTerritorialPlanHormiga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=160)),
                ("dpi", models.CharField(blank=True, max_length=20, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=15,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "centro_votacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enlaces_plan_hormiga",
                        to="afiliados_app.centrovotacion",
                    ),
                ),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enlaces_plan_hormiga",
                        to="afiliados_app.comunidad",
                    ),
                ),
                (
                    "coordinador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enlaces",
                        to="afiliados_app.coordinadorplanhormiga",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enlaces_plan_hormiga",
                        to="afiliados_app.sector",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enlaces_plan_hormiga_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enlaces_plan_hormiga_modificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="EstructuraPlanHormiga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_estructura", models.CharField(max_length=80)),
                ("nombre", models.CharField(max_length=160)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=15,
                    ),
                ),
                ("cantidad_integrantes", models.PositiveIntegerField(default=0)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "centro_votacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estructuras_plan_hormiga",
                        to="afiliados_app.centrovotacion",
                    ),
                ),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estructuras_plan_hormiga",
                        to="afiliados_app.comunidad",
                    ),
                ),
                (
                    "coordinador_responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estructuras_responsables",
                        to="afiliados_app.coordinadorplanhormiga",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estructuras_plan_hormiga",
                        to="afiliados_app.sector",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estructuras_plan_hormiga_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estructuras_plan_hormiga_modificadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="ResponsableZonaPlanHormiga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=160)),
                ("dpi", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=15,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "centro_votacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsables_plan_hormiga",
                        to="afiliados_app.centrovotacion",
                    ),
                ),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsables_plan_hormiga",
                        to="afiliados_app.comunidad",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsables_plan_hormiga",
                        to="afiliados_app.sector",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsables_plan_hormiga_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsables_plan_hormiga_modificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="PuntoVisitadoPlanHormiga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_visitada", models.PositiveIntegerField(default=0)),
                ("fecha", models.DateField()),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="puntos_visitados_plan_hormiga",
                        to="afiliados_app.comunidad",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="puntos_visitados_plan_hormiga",
                        to="afiliados_app.sector",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="puntos_visitados_plan_hormiga_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="puntos_visitados_plan_hormiga_modificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="puntos_visitados",
                        to="afiliados_app.responsablezonaplanhormiga",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="IncidenciaPlanHormiga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_incidencia", models.CharField(max_length=120)),
                ("descripcion", models.TextField()),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                        ],
                        default="MEDIA",
                        max_length=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=15,
                    ),
                ),
                ("seguimiento", models.TextField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "centro_votacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidencias_plan_hormiga",
                        to="afiliados_app.centrovotacion",
                    ),
                ),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidencias_plan_hormiga",
                        to="afiliados_app.comunidad",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidencias_plan_hormiga",
                        to="afiliados_app.sector",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidencias_plan_hormiga_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidencias_plan_hormiga_modificadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsable_asignado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidencias_asignadas",
                        to="afiliados_app.responsablezonaplanhormiga",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="CompromisoTerritorialPlanHormiga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actividad", models.CharField(max_length=180)),
                ("fecha_compromiso", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_CURSO", "En curso"),
                            ("CUMPLIDO", "Cumplido"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compromisos_plan_hormiga",
                        to="afiliados_app.comunidad",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compromisos_plan_hormiga_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compromisos_plan_hormiga_modificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compromisos",
                        to="afiliados_app.responsablezonaplanhormiga",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_compromiso", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ActivacionTerritorialPlanHormiga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_accion", models.CharField(max_length=150)),
                ("fecha", models.DateField()),
                ("resultado", models.TextField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activaciones_plan_hormiga",
                        to="afiliados_app.comunidad",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activaciones_plan_hormiga_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activaciones_plan_hormiga_modificadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activaciones",
                        to="afiliados_app.responsablezonaplanhormiga",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ReunionPlanHormiga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo_reunion",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("titulo", models.CharField(max_length=180)),
                ("responsables", models.TextField(blank=True, null=True)),
                (
                    "responsable_tipo",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "responsable_referencia_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("asistentes", models.PositiveIntegerField(default=0)),
                ("acuerdos", models.TextField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "estado_seguimiento",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En proceso"),
                            ("CUMPLIDO", "Cumplido"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "centro_votacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reuniones_plan_hormiga",
                        to="afiliados_app.centrovotacion",
                    ),
                ),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reuniones_plan_hormiga",
                        to="afiliados_app.comunidad",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reuniones_plan_hormiga",
                        to="afiliados_app.sector",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reuniones_plan_hormiga_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reuniones_plan_hormiga_modificadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SeguimientoContactoPlanHormiga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("persona_contactada", models.CharField(max_length=160)),
                ("dpi", models.CharField(blank=True, max_length=20, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "estado_seguimiento",
                    models.CharField(
                        choices=[
                            ("NUEVO", "Nuevo"),
                            ("EN_PROCESO", "En proceso"),
                            ("CERRADO", "Cerrado"),
                        ],
                        default="NUEVO",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_ultimo_contacto", models.DateField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seguimientos_plan_hormiga",
                        to="afiliados_app.comunidad",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seguimientos_plan_hormiga_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seguimientos_plan_hormiga_modificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_actualizacion"],
            },
        ),
        migrations.CreateModel(
            name="VisitaPlanHormiga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo_visita",
                    models.CharField(
                        choices=[
                            ("CASA_CASA", "Casa a casa"),
                            ("RECORRIDO", "Recorrido"),
                            ("REUNION", "Reunión"),
                        ],
                        default="RECORRIDO",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=15,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitas_plan_hormiga",
                        to="afiliados_app.comunidad",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitas",
                        to="afiliados_app.responsablezonaplanhormiga",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitas_plan_hormiga",
                        to="afiliados_app.sector",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visitas_plan_hormiga_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visitas_plan_hormiga_modificadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EstructuraIntegrantePlanHormiga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dpi", models.CharField(max_length=20)),
                ("nombre_completo", models.CharField(max_length=180)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=15,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integrantes_estructura_plan_hormiga",
                        to="afiliados_app.comunidad",
                    ),
                ),
                (
                    "usuario_registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integrantes_estructura_plan_hormiga_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estructura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrantes",
                        to="afiliados_app.estructuraplanhormiga",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_registro"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("estructura", "dpi"),
                        name="uniq_estructura_plan_hormiga_integrante_dpi",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanHormigaIntegrante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("REVISADO", "Revisado"),
                            ("APROBADO", "Aprobado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "afiliado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_plan_hormiga",
                        to="afiliados_app.afiliado",
                    ),
                ),
                (
                    "usuario_modificacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integrantes_plan_hormiga_modificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integrantes_plan_hormiga_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Integrante de Plan Hormiga",
                "verbose_name_plural": "Integrantes de Plan Hormiga",
                "ordering": ["-fecha_creacion"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("afiliado",), name="uniq_plan_hormiga_afiliado"
                    )
                ],
            },
        ),
    ]
